### ISSUE TITLE
Adapter file

### ISSUE THREAD

**Issue by mjoh223** [mmarbout/HGP-Hi-C#1]
Hi! I was wondering what adapter file should be used for the **1_assembly.sh** script? 
Thanks.

**Comment by mmarbout** [comment]
You have to use the TruSeq DNA sequences from illumina
Adapter Trimming
The following sequences are used for adapter trimming.
Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

**Comment by mjoh223** [comment]
thanks, great paper!
